# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libromodelo',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
