# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libromodelo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='libromodelo',
            name='tipo',
            field=models.CharField(blank=True, default='Libro', max_length=40, null=True),
        ),
    ]
